SentinelsOfMagic/SentinelsOfMagic

app.json

Reverts SentinelsOfMagic/SentinelsOfMagic#6

Revert "update app.json with start script"

---

database/fridgr.sql
package.json

Database schema

---

client/src/houseInventory.jsx

- update app state with results from GET request on refresh
- propagate items list to HouseInventoryList component

Add ajax GET request to populate items list

---

.gitignore
README.md
database/index.js
package.json

This should be working, need routes and attempted access or tests or something but SHOULD work. Heroku is set up with Postgres so 50% chance this can go live without exploding.

Database setup complete

---

.gitignore
package.json
webpack.config.js

- Add webpack dependencies to package.json
- Update .gitignore

Configure webpack for multiple entry points

---

client/src/components/HouseInventoryList.jsx
client/src/components/HouseInventoryListItem.jsx
client/src/components/houseInventory.jsx
client/src/index.jsx
database/dummyData.js
server/index.js

Pushing my WIP code so that I don't lose it again!

WIP: add shell server-side functions for House Inventory, change ajax to axios, general code clean up

---

package.json

There's probably a fancy way of doing this that would be good to learn but I really want to see our app live!

Add webpack to normal dependencies

---

client/dist/index.html
client/dist/style.css
client/src/components/Base.jsx
client/src/components/Homepage.jsx
client/src/components/LoginForm.jsx
client/src/components/SignupForm.jsx
client/src/containers/LoginPage.jsx
client/src/containers/SignUpPage.jsx
client/src/index.jsx
package.json

Everything is showing up on the root page right now so just ignore the login/signup while you work on your components.

Add login/signup client components

---

client/src/components/HouseInventoryList.jsx
client/src/components/HouseInventoryListItem.jsx
client/src/components/houseInventory.jsx
database/fridgr.sql
database/index.js
package.json
server/index.js

Add functionality for server to consume POST request to path /inventory

---

client/src/components/CreateUser.jsx
client/src/components/ShoppingListItem.jsx
client/src/components/shoppingList.jsx
client/src/index.jsx
database/models/shoppingList.js
server/index.js
server/lib/route-handlers.js

Also added get('*', ...) in server at end of routes, by serving up the homepage, passes route into the react-router. Allows routes to be reached from outside world.

Shopping list queries database

---

client/src/components/SelectUser.jsx
client/src/index.jsx
package.json
server/index.js
server/lib/auth.js

- change /User route to /user
- uninstall validator npm module (not needed)

Add auth.js to handle signup/login routes on server side

---

database/fridgr.sql
database/index.js
database/models/shoppingList.js
package.json

- Select items from users private list as well as public list
- Uncomment database connections

Update database with autoincrementing primary keys

---

client/src/components/LoginForm.jsx
client/src/components/SignUpForm.jsx
client/src/containers/LoginPage.jsx
client/src/containers/SignUpPage.jsx
package.json
server/index.js
server/lib/auth.js
server/lib/hashUtils.js

- successful signup now redirects to login with success message
- add code to generate salt/hash for password
- add crypto module to package.json

Connect signup to database! =)

---

client/src/containers/LoginPage.jsx
client/src/containers/SignUpPage.jsx
server/lib/auth.js

- login form now checks database for matching house name and password
- login also handles non-matching cases and displays error message
- add code to auth.js to check if house name is taken when signing up

Process login

---

client/src/components/ShoppingListItem.jsx
client/src/components/shoppingList.jsx
database/fridgr.sql
database/models/shoppingList.js
server/index.js
server/lib/route-handlers.js

- Check boxes and purchase
- Rebase on top of rebase for double the commits!
- Bug, boxes don't uncheck themselves on submission, messes up checked/unchecked statekeeping

94% working shopping list

---

client/src/components/CreateUser.jsx
client/src/containers/LoginPage.jsx
package.json
server/index.js
server/lib/auth.js

- add code to /login route handler in auth.js to query users from DB
- redirect to either CreateUser or SelectUser upon login
- add code to send cookie from server
- add cookie-parser to package.json
- change /login post handler in auth.js to use db.one instead of db.query

Redirect from LoginPage to corresponding component

---

client/src/components/AddItem.jsx
client/src/components/AddItemForm.jsx
client/src/components/HouseInventoryList.jsx
client/src/components/houseInventory.jsx
client/src/index.jsx
database/fridgr.sql
server/index.js

Still need to fix asynchronous behavior for adding items that don't already exist in the items table.

WIP AddItem functionality for existing items only

---

server/index.js

Works now for both items that already exist in the items table, and new items.
Auto-reloads list with added items.

Complete Add Item functionality

---

client/src/components/Base.jsx
client/src/components/Nav.jsx
client/src/components/houseInventory.jsx
client/src/components/shoppingList.jsx

Unable to action a redirect when the title is clicked.

Complete Nav bar styling and WIP Base component styling

---

client/dist/index.html
client/dist/style.css
client/src/components/AddItem.jsx
client/src/components/AddItemForm.jsx
client/src/components/Base.jsx
client/src/components/HouseInventoryList.jsx
client/src/components/HouseInventoryListItem.jsx
client/src/components/houseInventory.jsx

Need to add Cancel button, if user does not wish to fill out Add Item form
Need to add conditions so that the user cannot submit the form with empty fields

Complete HouseInventory styling, need to add some front-end functionality

---

client/src/components/AddItem.jsx
client/src/components/AddItemForm.jsx
client/src/components/Nav.jsx
server/index.js
server/lib/inventoryUtils.js

Still need to hook up the cookies.

Complete HouseInventory styling and logic for AddItem

---

client/src/components/AddItem.jsx
client/src/components/AddItemForm.jsx
client/src/components/Base.jsx
client/src/components/HouseInventoryList.jsx
client/src/components/HouseInventoryListItem.jsx
client/src/components/Nav.jsx
client/src/components/houseInventory.jsx
server/index.js

Fixed deletion bug
Fixed add item bug
Using house_id from cookies
Still using dummy data user_id

Fix bugs in HouseInventory

---

database/fridgr.sql
database/models/session.js
server/index.js
server/lib/route-handlers.js
server/middleware/authorizedRequest.js

Add middleware directory and session model

---

server/middleware/authorizedRequest.js

NOTE: Not integrated yet, will be integrated once session adding middleware is in place

Add authorized route checking middleware

---

client/dist/style.css
client/src/components/Base.jsx
client/src/components/CreateUser.jsx
client/src/components/SelectUser.jsx
client/src/components/houseInventory.jsx
client/src/containers/LoginPage.jsx
server/index.js
server/lib/auth.js
server/middleware/assignCookie.js

- Add middleware to assign cookies
+ for every path, assign a cookie and insert into sessions table if there are none
- LoginPage now updates cookie and sessions table with houseId upon login
- SelectUser and CreateUser components now update cookie and sessions table with userId upon user selection
- Refactor cookie parser code in houseInventory.jsx to get houseId and userId
- Update Link colors

Add code for new cookies/sessions

---

client/src/components/CreateUser.jsx
client/src/components/UserList.jsx

Fix CreateUser bug

---

client/src/components/CreateUser.jsx
client/src/components/HomePage.jsx
client/src/components/houseInventory.jsx
server/index.js

- bug: clicking on main ‘Fridgr' title before user is selected will result in error when
clicking on inventory or shopping list afterwards
+ fix: add redirect to HomePage's componentWillMount to redirect to previous page if
userId is not in the cookie
- bug: houseInventory's redirect in componentWillMount breaks
+ fix: change redirect conditions to check if houseId or userId is null

Fix 'redirect' bugs
